spring:
  application:
    name: rag4j

  profiles:
    active: local


openai:
  api-key: ${{ secrets.APP_KEY }} # OpenAI API 키
  base-url: https://api.openai.com/v1/  # OpenAI API 기본 URL
  model: gpt-4-turbo  # 사용할 모델 이름 (GPT-4 Turbo)
  timeout: 30