server:
  port: 8082
  host: http://localhost

spring:
  application:
    name: rag4j
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/rag4j
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rag4j-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

## JWT
jwt:
  issuer: "rag4j"
  secret-key: "vphCLJGXSToCwwUnhATo8i8TDObsODt+tEYCfMCiFsI="
  access-token:
    expiration: 99999999999999999
  refresh-token:
    expiration: 99999999999999999

chroma:
  host: http://localhost:8000
  username: root
  password: root

openai:
  api:
    url: https://api.openai.com/v1/embeddings
    key: sk-proj-Ir2IlDX9f75AxluNdRcXxa0QeArB5Bgz9qmf6zNr6OKkQ1zg5hEJw4NcWIMNrde5_CebrlVMLhT3BlbkFJ8umLmDcU-hOZJwb35x1O2VcqOjWAjsFl42lla8_Hu5Nt3gD9CQ-UAE-7nJCjRCkY3ysscwfQEAgit remote add upstream https://github.com/Dplo1514/rag4j.git

## S3
cloud:
  drive:
    credentials:
      file-path: src/main/resources/static/google_cloud_credentials.json
    application:
      name: raf4jProject