version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: rag4j
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: >
      bash -c "
      docker-entrypoint.sh mysqld &
      sleep 30 &&
      mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS rag4j;' &&
      mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS rag4j_test;' &&
      mysql -u root -proot -e 'CREATE USER IF NOT EXISTS \"root\"@\"%\" IDENTIFIED BY \"root\";' &&
      mysql -u root -proot -e 'GRANT ALL PRIVILEGES ON rag4j.* TO \"root\"@\"%\";' &&
      mysql -u root -proot -e 'GRANT ALL PRIVILEGES ON rag4j_test.* TO \"root\"@\"%\";' &&
      mysql -u root -proot -e 'FLUSH PRIVILEGES;' &&
      wait
      "
    volumes:
      - ./mysql:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
