version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: rag4j
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: >
      bash -c "
      docker-entrypoint.sh mysqld &
      sleep 30 &&
      mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS rag4j;' &&
      mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS rag4j_test;' &&
      mysql -u root -proot -e 'CREATE USER IF NOT EXISTS \"root\"@\"%\" IDENTIFIED BY \"root\";' &&
      mysql -u root -proot -e 'GRANT ALL PRIVILEGES ON rag4j.* TO \"root\"@\"%\";' &&
      mysql -u root -proot -e 'GRANT ALL PRIVILEGES ON rag4j_test.* TO \"root\"@\"%\";' &&
      mysql -u root -proot -e 'FLUSH PRIVILEGES;' &&
      wait
      "
    volumes:
      - ./mysql:/var/lib/mysql

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest  # 최신 ChromaDB 이미지 사용
    container_name: chromadb_container
    ports:
      - "8000:8000"  # ChromaDB의 기본 포트 5000을 외부에 노출
    restart: always
    environment:
      - CHROMADB_SERVER_HOST=0.0.0.0  # 모든 IP에서 접근 가능하게 설정
      - CHROMADB_SERVER_PORT=5000  # 사용할 포트 설정
